### ISSUE TITLE
equipment

### ISSUE THREAD

**Issue by LeeHaoRanRan** [iolag/UPD_study#8]
How much memory and what type of video card did you use in the experiment

**Comment by iolag** [comment]
Hi, we used an Nvidia Quadro RTX 8000 GPU and an AMD Ryzen Threadripper 3960X CPU for the experiments. I don't know about the memory though, but I'm sure it was on the higher side. I'm sure one could easily run the experiments on a less powerful system though.

**Comment by LeeHaoRanRan** [comment]
Thank you for your reply, but the following problems occur when I run it？
![image](https://github.com/user-attachments/assets/289d1c6c-310e-415b-8e83-237b36e8f87e)

**Comment by LeeHaoRanRan** [comment]
train_loader, val_loader, big_testloader, small_testloader = load_data(config)，The code before this will be executed repeatedly
